repos:
  - repo: "local"
    hooks:
      - id: "clang-format"
        name: "clang-format"
        language: "system"
        always_run: false
        entry: "clang-format -style=file -i"
        exclude: "(^(Attic|build)/.*$)|(CMakeFiles)"
        fail_fast: false
        files: ""
        pass_filenames: true
        require_serial: false
        stages: ["commit"]
        types: ["file"]
        types_or: ["c", "c++"]
        verbose: true
