FROM ubuntu:focal
RUN apt update
RUN yes | apt install wget sudo
RUN wget http://www.flopoco.org/install_scripts/install-plain-gitmaster-on-focal64.sh
RUN yes | sh install-plain-gitmaster-on-focal64.sh

VOLUME ["/flopoco_workspace"]

ENTRYPOINT ["/flopoco/build/flopoco"]

WORKDIR /flopoco_workspace
