[package]
name = "autotests-html"
version = "0.1.0"
edition = "2021"

[dependencies]
build_html = "2.4.0"
csv = "1.3.0"
serde = { version = "1.0.203", features = ["derive"] }
strum = { version = "0.26.3", features = ["derive", "strum_macros"] }
